// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA47UaIEEYm4tslR7wuIruiMEKXn1mSgrw',
    appId: '1:565968896814:web:9162631f4bf1b95b5eb0bf',
    messagingSenderId: '565968896814',
    projectId: 'chat-application-945f8',
    authDomain: 'chat-application-945f8.firebaseapp.com',
    storageBucket: 'chat-application-945f8.firebasestorage.app',
    measurementId: 'G-TGZY9JJ794',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDojrP8wuq1uOgjY_7derLvYvHPAAR0mm0',
    appId: '1:565968896814:android:bba5d80d946c88225eb0bf',
    messagingSenderId: '565968896814',
    projectId: 'chat-application-945f8',
    storageBucket: 'chat-application-945f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC03CsTJXcLdF7x-k-EfTkzH0p2fc1_zI',
    appId: '1:565968896814:ios:87cdd83d25d434045eb0bf',
    messagingSenderId: '565968896814',
    projectId: 'chat-application-945f8',
    storageBucket: 'chat-application-945f8.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );
}
